[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "signals and systems python project"
version = "1.0.0"
description = "A Python project for generating, transforming, and visualizing basic signals such as sinusoidal and step functions for the Signals and Systems course."
authors = [
    {name = "Shaoyu Wu", email = "shaoyu.wu@student.tudelft.nl"}
]
dependencies = [
    "numpy>=1.20",
    "matplotlib>=3.5",
    "pytest>=7.0"
]
readme = "README.md"
requires-python = ">=3.8"